### ISSUE TITLE
Allow generation of RSA keys longer than 2048 bits

### ISSUE THREAD

**Issue by elipsion** [philipWendland/IsoApplet#22]
When upgrading to Java Card 3.0.4, it would be beneficial to support longer keys (i.e. 3072 and 4096).
The full list of key lengths is listed [here](https://docs.oracle.com/javacard/3.0.5/api/constant-values.html#javacard.security.KeyBuilder.LENGTH_RSA_1024); I guess it couldn't hurt to add the shorter ones at the same time.

**Comment by elipsion** [comment]
I would love to make a PR on this, but I don't have access to the relevant ISO documentation. Feel free to reach out to me for further assistance.

**Comment by philipWendland** [comment]
I agree that 4096 bit RSA should be added for 3.0.4. I started implementing this, as I am stuck with the ECC part of the 3.0.4 features. 
These large keys might require more changes under the hood; extended length APDUs might become a requirement.

**Comment by elipsion** [comment]
There has been some development in [a fork by llogar](https://github.com/llogar/IsoApplet/tree/v5), but I don't know how compatible it is.

**Comment by philipWendland** [comment]
Thanks. 
I'm closing this, see #23. The requirement of 4096 bit RSA support is noted for future versions.
