### ISSUE TITLE
Supported card SmartCafe Expert 3.2 doesn't work

### ISSUE THREAD

**Issue by jacobsevart** [philipWendland/IsoApplet#7]
I purchased a couple of SmartCafe Expert 3.2 cards per the Wiki's recommendation, but this model uses JavaCard 2.2.1. Consequently, I was not able to install any applets on them. All the ones I tried - MuscleApplet, IsoApplet, and ykneo-openpgp - failed with an error similar to this one. (Unlocking was successful, though.)

```
➜  GlobalPlatformPro git:(master) ✗ gp -install AppletPlayground/MuscleApplet.cap -default
Applet loading failed. Are you sure the CAP file (JC version, packages) is compatible with your card?
pro.javacard.gp.GPException: LOAD failed SW: 6A80
	at pro.javacard.gp.GlobalPlatform.check(GlobalPlatform.java:1092)
	at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:728)
	at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:686)
	at pro.javacard.gp.GPTool.main(GPTool.java:471)
➜  GlobalPlatformPro git:(master) ✗
```

I assume this error is referring to the fact that the card is JC 2.2.1. Is it possible to compile any OpenSC-compatible applet for 2.2.1? If not, I would recommend removing any 2.2.1 cards/purchase links from the hardware recommendations.

**Comment by jacobsevart** [comment]
Whoops, meant to file this against GlobalPlatformPro

**Comment by martinpaljak** [comment]
Well, I think the issue is relevant here, and should read "IsoApplet does not run on G&D SCE 3.2"

**Comment by philipWendland** [comment]
I've got a Smartcafe 6.0 card, it seems to work fine ater some simple tests. IsoApplet's minimum Java Card version is 2.2.2, so this should be the reason. AFAIK, the M.U.S.C.L.E. applet is from 2001, so there is a high chance that this is compile-able with 2.2.1. 

However, the M.U.S.C.L.E. applet seems to not load on any of my cards (both the 3.0.1 version from martinpaljak's applet playground and an older binary from the M.U.S.C.L.E. page that i found.). You should try to compile the muscle applet yourself with 2.2.1 from source, I guess this is your best bet.

I will make some extended tests on cards I own and will make a list of tested smart cards for the IsoApplet when I get back home next week.
